### PR TITLE
Add isHavingAlias to ResultColumn

### PR DESCRIPTION
**Pull request by repo-wiseacre**
For validation purpose if we can include one more variable in order to know whether the sql is having the aliasName or it is taking the column names by default.

### CODE REVIEW

**Comment by nathanlws** [comment]
The `exposedName` is already the alias when one is provided and the an original can be found (if there is one) by checking if `getExpression()` is a `ColumnReference`.

Do you have a use case where that doesn't work?

**Comment by repo-wiseacre** [comment]
You are correct @nathanlws but as I have seen in this class file if the sql query doesn't have the column alias it takes the column name by default which makes the validation difficult if the scenario when providing alias name is mandatory.

**Comment by nathanlws** [comment]
If your application requires an alias distinct from the source column name, couldn't that be checked with something like below?

```
void checkForAlias(ResultColumn rc) {
  if(rc.getExpression() instanceof ColumnReference) {
    ColumnReference ref = (ColumnReference)rc.getExpression();
    if(!rc.getName().equalsIgnoreCase(ref.getColumnName())) {
      throw new ColumnAliasRequiredException();
    }
  }
}
```

**Comment by repo-wiseacre** [comment]
In that case suppose the user is providing a query say "Select emp.employee_id from M_EMPLOYEE_TABLE then what would be the content of the resultcolumn instance is rc.getName will be employee_id and rc.getExpression().getColumnName will also be employee_id since ref.getColumnName() is employee_id. As a result there is no chance of throwing the exception in any scenario if I am not wrong.

**Comment by nathanlws** [comment]
Your example query would get an exception with my (edited to remove `!`) code snippet. That is, an exception would be thrown if 1) there is no alias provided or 2) the alias matches the source column name. Is that the behavior you want?

I'm not strictly opposed to adding the variable from this PR but I just want to make sure its actually required.

**Comment by repo-wiseacre** [comment]
See @nathanlws the user can also provide the same alias name as what is the column name with respect to a particular query. Then that is the most positive case of the scenario. But if the user doesn't provide the alias name at all. Only for that case I want to throw the exception. The code which you have provided in the above will work for that particular case then it is fine with me and that is what I want.

**Comment by repo-wiseacre** [comment]
Any more coments to this discussion you want to put into ? @nathanlws

**Comment by repo-wiseacre** [comment]
Even after (edit and remove !) to the code snippet will not work @nathanlws

**Comment by nathanlws** [comment]
I understand your use case now, thanks for the elaboration.

I think the existing `name` field could be utilized instead of adding another. How about making name correspond to the ColumnReference and exposedName correspond to the alias?

**Comment by repo-wiseacre** [comment]
Yes you may go with the existing field but be sure that no regression issue comes up because many of the module may use that field either locally or remotely. Making name correspond to the ColumnReference is a good idea and it will be more specific it seems @nathanlws

**Comment by repo-wiseacre** [comment]
I think the existing name field could be utilized. For that I have to change the existing code in couple of places. If you agreeing with me then let me send another pull request @nathanlws .

**Comment by nathanlws** [comment]
After some more digging, re-purposing either of the existing fields are problematic I think. Compatibility is a bugger.

Would would you think of `boolean hasAlias`, which would be set to (arg1 != null) in the first cast in init() (and in setName()?). I suggest that as the difference between exposedName and aliasName is otherwise minimal.

**Comment by repo-wiseacre** [comment]
Perfect. Even I also thought of this. Shall I change to the same and send you the final pull request ? @nathanlws

**Comment by nathanlws** [comment]
Sounds good. Feel free to update this PR or open a new one, either way is just fine.

**Comment by repo-wiseacre** [comment]
Please have a look at the code @nathanlws and if it is correct please commit.

**Comment by repo-wiseacre** [comment]
Please address the latest.

**Comment by nathanlws** [comment]
Looks as discussed. Thanks for being so flexible @repo-wiseacre!

Approve

**Comment by nathanlws** [comment]
Build error:

```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/akiba/workspace/parser-build/src/main/java/com/foundationdb/sql/parser/ResultColumn.java:[143,48] error: inconvertible types
```

You'll need to wrap the cast of arg2 in another set of parens.

**Comment by repo-wiseacre** [comment]
@nathanlws ,
Apologize for the silly mistake I did. I have fixed and so creating one more PR.
This is the first time ever I am contributing to a development and I am glad that its Foundation db

Thanks @nathanlws

**Comment by repo-wiseacre** [comment]
@nathanlws is it okay ?

**Comment by nathanlws** [comment]
Yep. Looks good for another go.

Approve

**Comment by repo-wiseacre** [comment]
Thanks a lot @nathanlws

**Pull request merged**
